---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    # This needs to be in place for the rspec-puppet Hiera 5 hook to work
    # No idea why, it may be because Puppet sees a custom backend and loads all
    # of the global parts.
    #compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    compliance_markup:
      repo: https://github.com/trevor-vaughan/pupmod-simp-compliance_markup
      branch: SIMP-6797
    concat: https://github.com/simp/puppetlabs-concat
    haveged: https://github.com/simp/pupmod-simp-haveged
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    # used in the acceptance test
    selinux: https://github.com/simp/pupmod-simp-selinux
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    stunnel: "#{source_dir}"
